# Generated by Django 5.2.7 on 2025-11-10 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='ExperienceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('vacancy_id', models.AutoField(primary_key=True, serialize=False)),
                ('job_title_nm', models.CharField(max_length=300, verbose_name='Название вакансии')),
                ('lower_bound_salary_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Минимальная зарплата')),
                ('upper_bound_salary_amt', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Максимальная зарплата')),
                ('vacancy_publish_dttm', models.DateTimeField(auto_now_add=True, verbose_name='Дата публикации')),
                ('vacancy_archive_flg', models.BooleanField(default=False, verbose_name='Архивная')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.area', verbose_name='Регион')),
                ('employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.employer', verbose_name='Работодатель')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.employmenttype', verbose_name='Тип занятости')),
                ('experience_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.experiencetype', verbose_name='Требуемый опыт')),
                ('job_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.jobcategory', verbose_name='Категория работы')),
                ('salary_currency', models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.currency', verbose_name='Валюта')),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancy',
                'ordering': ['-vacancy_publish_dttm'],
            },
        ),
    ]
